# Generated by Django 3.0.3 on 2020-03-03 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='UserProfile')),
            ],
        ),
    ]
