# Generated by Django 3.0.3 on 2020-03-03 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('expiration_date', models.DateTimeField(auto_now_add=True, verbose_name='Experience')),
                ('file', models.FileField(upload_to='upload/file', verbose_name='Archive')),
                ('cover', models.ImageField(upload_to='upload/cover', verbose_name='Cover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
